### ISSUE TITLE
pTracks crashes

### ISSUE THREAD

**Issue by MrBeBo999** [wiedehopf/tar1090#121]
On my android phone and linux laptop pTracks crashes or takes minutes to open, utilizing 100% of processor time. When this happens, the pi where tar1090 is running has absolutely no sweat. So I think it is the building of the tracks in the browser that  is heavy or crashing.

**Comment by wiedehopf** [comment]
You can do less hours ... /?ptracks=4 for 4 hours.

If your browser/device can't handle it that's too bad :/
I could probably display lots of dots instead of the tracks from the same data and use webGL for those dots.
But it wouldn't be tracks... might still be nice.

No way to do the lines with webGL at the moment.
