### ISSUE TITLE
Filter by country of registration

### ISSUE THREAD

**Issue by orangy** [wiedehopf/tar1090#180]
I couldn't find if it's possible to show only planes with a specific country of registration. Help, and even query filters manual doesn't mention it. Thanks!

**Comment by wiedehopf** [comment]
There is not such feature.

You can filter by hex id though.

**Comment by orangy** [comment]
I don't know much about the aviation systems yet, just learning :) Does hex id somehow encode country?

**Comment by denhamgithub** [comment]
http://www.aerotransport.org/html/ICAO_hex_decode.html  for blocks of hex codes by country.  You also will find that the A/Craft Registration numbers are by country.  And also are similar to the radio/TV ID's for that country.

Just stumbled onto to your mid-April post and perhaps you've already found the answers to the Q's you raised.

Otherwise, hope you enjoy this hobby as much as me.

**Comment by mpentler** [comment]
![image](https://user-images.githubusercontent.com/27921983/203029567-c22440f1-2c60-4a6c-ac0a-0d8d6c176a18.png)
??

Did this get added without any fanfare? I was about to try working on it.
