### ISSUE TITLE
Strong messages are not counted

### ISSUE THREAD

**Issue by dxmekch** [wiedehopf/tar1090#43]
Good morning

With --gain -10 everything is fine and strong signals will be counted and written down in stats.json. with --gain 50 or 45 or every other value, strong signals is always 0.

Question: what's the difference between "enable-agc" and "--gain -10"?

Thanks

**Comment by wiedehopf** [comment]
-10 is the setting to enable AGC which basically results in a gain of 58 or so.

See also this snippet:
Using a gain of -10 turns on AGC (Automatic Gain Control).
Due to ADS-B only being short bursts of data, it usually sets gain as if it were set to about 58, which is more than you can set with the manual gain settings.
(58 not being available as manual gain is a shortcoming of the rtl-sdr drivers)
Available manual gain settings:
0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4
28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
